"""Constants used when converting."""

# Named data variables (ie data)
# All other columns considered as metadata / coordinates
DATA_VARIABLE_COLUMNS = [
    "FLOAT_DATA",
    "DATA",
    "CORRECTED_DATA",
    "WEIGHT_SPECTRUM",
    "WEIGHT",
    "FLAG",
    "UVW",
    "TIME_CENTROID",
    "EXPOSURE",
    "FLAG_CATEGORY",
    "MODEL_DATA",
    "SIGMA",
    "ARRAY_ID",
    "DATA_DESC_ID",
    "FEED1",
    "FEED2",
    "FIELD_ID",
    "FLAG_ROW",
    "INTERVAL",
    "OBSERVATION_ID",
    "PROCESSOR_ID",
    "SCAN_NUMBER",
    "STATE_ID",
]

# Rename MS columns to a DataArray/ Dataset variable
COLUMN_TO_DATA_VARIABLE_NAMES = {
    "FLOAT_DATA": "SPECTRUM",
    "DATA": "VISIBILITY",
    "CORRECTED_DATA": "VISIBILITY_CORRECTED",
    "WEIGHT_SPECTRUM": "WEIGHT_SPECTRUM",
    "WEIGHT": "WEIGHT",
    "FLAG": "FLAG",
    "UVW": "UVW",
    "TIME_CENTROID": "TIME_CENTROID",
    "EXPOSURE": "EFFECTIVE_INTEGRATION_TIME",
    "U": "U",
    "V": "V",
    "W": "W",
    "FLAG_CATEGORY": "FLAG_CATEGORY",
    "MODEL_DATA": "MODEL_DATA",
    "SIGMA": "SIGMA",
    "ARRAY_ID": "ARRAY_ID",
    "DATA_DESC_ID": "DATA_DESC_ID",
    "FEED1": "FEED1",
    "FEED2": "FEED2",
    "FIELD_ID": "FIELD_ID",
    "FLAG_ROW": "FLAG_ROW",
    "INTERVAL": "INTERVAL",
    "OBSERVATION_ID": "OBSERVATION_ID",
    "PROCESSOR_ID": "PROCESSOR_ID",
    "SCAN_NUMBER": "SCAN_NUMBER",
    "STATE_ID": "STATE_ID",
}

# The dimensions of a given column
COLUMN_DIMENSIONS = {
    "DATA": ("time", "baseline_id", "frequency", "polarization"),
    "CORRECTED_DATA": ("time", "baseline_id", "frequency", "polarization"),
    "WEIGHT_SPECTRUM": ("time", "baseline_id", "frequency", "polarization"),
    "WEIGHT": ("time", "baseline_id", "polarization"),
    "FLAG": ("time", "baseline_id", "frequency", "polarization"),
    "UVW": ("time", "baseline_id"),
    "U": ("time", "baseline_id"),
    "V": ("time", "baseline_id"),
    "W": ("time", "baseline_id"),
    "TIME_CENTROID": ("time", "baseline_id"),
    "EXPOSURE": ("time", "baseline_id"),
    "FLOAT_DATA": ("time", "baseline_id", "frequency", "polarization"),
    "FLAG_CATEGORY": ("time", "baseline_id", "frequency", "polarization"),
    "MODEL_DATA": ("time", "baseline_id", "frequency", "polarization"),
    "SIGMA": ("time", "baseline_id", "polarization"),
    "ARRAY_ID": ("time", "baseline_id"),
    "DATA_DESC_ID": ("time", "baseline_id"),
    "FEED1": ("time", "baseline_id"),
    "FEED2": ("time", "baseline_id"),
    "FIELD_ID": ("time", "baseline_id"),
    "FLAG_ROW": ("time", "baseline_id"),
    "INTERVAL": ("time", "baseline_id"),
    "OBSERVATION_ID": ("time", "baseline_id"),
    "PROCESSOR_ID": ("time", "baseline_id"),
    "SCAN_NUMBER": ("time", "baseline_id"),
    "STATE_ID": ("time", "baseline_id"),
}

# Rename coordinate columns to something sensible
COLUMN_TO_COORDINATE_NAMES = {
    "TIME": "time",
    "ANTENNA1": "baseline_antenna1_id",
    "ANTENNA2": "baseline_antenna2_id",
}

# Polarization IDs to Stokes parameter name
STOKES_TYPES = {
    0: "Undefined",
    1: "I",
    2: "Q",
    3: "U",
    4: "V",
    5: "RR",
    6: "RL",
    7: "LR",
    8: "LL",
    9: "XX",
    10: "XY",
    11: "YX",
    12: "YY",
    13: "RX",
    14: "RY",
    15: "LX",
    16: "LY",
    17: "XR",
    18: "XL",
    19: "YR",
    20: "YL",
    21: "PP",
    22: "PQ",
    23: "QP",
    24: "QQ",
    25: "RCircular",
    26: "LCircular",
    27: "Linear",
    28: "Ptotal",
    29: "Plinear",
    30: "PFtotal",
    31: "PFlinear",
    32: "Pangle",
}
